# Importing Libraries

In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import regex as re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import requests

C:\Users\vella\Anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vella\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vella\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

# Importing datasets

In [34]:
df1 = pd.read_csv(r"C:\Users\vella\Desktop\Praju\College\Projects\Final year\Data\Tesla_news.csv", encoding='cp1252')

In [36]:
df1['Date'] = pd.to_datetime(df1['Date'], errors = 'coerce')

In [37]:
df1

          Date                                          Headlines
0   2021-09-30  A flippant Elon Musk takes shots at Biden, the...
1   2021-09-30  Onetime big Tesla bull Chamath Palihapitiya sa...
2   2021-10-02  Tesla delivered 241,300 vehicles in the third ...
3   2021-10-03  Semiconductor chip shortage could extend throu...
4   2021-10-05  From Elon Musk’s thoughts on regulation to a $...
..         ...                                                ...
523 2022-09-21  Elon Musk says ‘patents are for the weak’ as h...
524 2022-09-24  Elon Musk has more than 20 direct reports at T...
525 2022-09-29   Tesla adds Airbnb co-founder Joe Gebbia to board
526 2022-09-30  Jack Dorsey tried to get Elon Musk on Twitter’...
527 2022-09-30  Tesla’s Optimus and the big questions in the q...

[528 rows x 2 columns]

# Performing sentiment analysis

In [38]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\vella\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [39]:
df1['scores'] = df1['Headlines'].apply(lambda Processed_tweet: sid.polarity_scores(Processed_tweet))
df1.head()

,Date,Headlines,scores
0,2021-09-30,"A flippant Elon Musk takes shots at Biden, the...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
1,2021-09-30,Onetime big Tesla bull Chamath Palihapitiya sa...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
2,2021-10-02,"Tesla delivered 241,300 vehicles in the third ...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
3,2021-10-03,Semiconductor chip shortage could extend throu...,"{'neg': 0.171, 'neu': 0.684, 'pos': 0.145, 'co..."
4,2021-10-05,From Elon Musk’s thoughts on regulation to a $...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."

In [40]:
df1['compound']  = df1['scores'].apply(lambda score_dict: score_dict['compound'])

In [41]:
df1.head(50)

,Date,Headlines,scores,compound
0,2021-09-30,"A flippant Elon Musk takes shots at Biden, the...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
1,2021-09-30,Onetime big Tesla bull Chamath Palihapitiya sa...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
2,2021-10-02,"Tesla delivered 241,300 vehicles in the third ...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
3,2021-10-03,Semiconductor chip shortage could extend throu...,"{'neg': 0.171, 'neu': 0.684, 'pos': 0.145, 'co...",-0.0772
4,2021-10-05,From Elon Musk’s thoughts on regulation to a $...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
5,2021-10-05,Tesla must pay $137 million to ex-worker over ...,"{'neg': 0.474, 'neu': 0.526, 'pos': 0.0, 'comp...",-0.7964
6,2021-10-05,Social network Commonstock aims to harness ret...,"{'neg': 0.0, 'neu': 0.851, 'pos': 0.149, 'comp...",0.2732
7,2021-10-05,"Tesla bucks market sell-off in past month, and...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
8,2021-10-06,Why Tesla has struggled with its solar business,"{'neg': 0.255, 'neu': 0.745, 'pos': 0.0, 'comp...",-0.3400
9,2021-10-07,GM-backed Cruise targets 1 million self-drivin...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
10,2021-10-08,Tesla moves headquarters from California to Texas,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
11,2021-10-08,"Musk moving Tesla headquarters to Austin, Texas","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
12,2021-10-08,"Elon Musk endorses a carbon tax, downplays con...","{'neg': 0.0, 'neu': 0.769, 'pos': 0.231, 'comp...",0.3400
13,2021-10-08,Stocks making the biggest moves premarket: Tes...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
14,2021-10-08,Here are key takeaways from Tesla’s annual inv...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
15,2021-10-08,8VC founder Joe Lonsdale on Elon Musk’s decisi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
16,2021-10-08,Tesla moving to Texas is a big win for the sta...,"{'neg': 0.0, 'neu': 0.759, 'pos': 0.241, 'comp...",0.5859
17,2021-10-08,"Jim Cramer on September jobs report, Tesla’s m...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
18,2021-10-09,"Bill Gates, Elon Musk and 4 other business lea...","{'neg': 0.0, 'neu': 0.756, 'pos': 0.244, 'comp...",0.6369
19,2021-10-10,"First Berlin Teslas could come next month, Elo...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
20,2021-10-11,"Tesla took 12 years to build 100,000 cars. Chi...","{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
21,2021-10-12,Tesla invites more drivers to ‘Full Self-Drivi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
22,2021-10-14,NHTSA asks Tesla why it didn’t initiate a reca...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
23,2021-10-14,Here are the best-selling electric cars in Chi...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
24,2021-10-15,Elon Musk is now worth $230 billion—as much as...,"{'neg': 0.0, 'neu': 0.881, 'pos': 0.119, 'comp...",0.2263
25,2021-10-17,Tesla’s Musk dials into Volkswagen executive c...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
26,2021-10-18,Kelly Evans: The lure of Tesla,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
27,2021-10-19,Morgan Stanley says SpaceX’s Starship may ‘tra...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
28,2021-10-20,SpaceX expected to become more valuable than T...,"{'neg': 0.0, 'neu': 0.764, 'pos': 0.236, 'comp...",0.5256
29,2021-10-20,Tesla posts record earnings but on one stock m...,"{'neg': 0.207, 'neu': 0.723, 'pos': 0.07, 'com...",-0.5927
30,2021-10-20,Bill Gates says climate tech will produce 8 to...,"{'neg': 0.0, 'neu': 0.892, 'pos': 0.108, 'comp...",0.1779
31,2021-10-21,Tesla posts record revenue and profits in thir...,"{'neg': 0.0, 'neu': 0.734, 'pos': 0.266, 'comp...",0.4404
32,2021-10-21,"Tesla earnings fail to boost the stock, but an...","{'neg': 0.118, 'neu': 0.785, 'pos': 0.097, 'co...",-0.1027
33,2021-10-21,NTSB finds driver seat was occupied in fatal T...,"{'neg': 0.36, 'neu': 0.64, 'pos': 0.0, 'compou...",-0.7351
34,2021-10-22,SpaceX test fires Starship as FAA reviews key ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
35,2021-10-25,Tesla hits $1 trillion market cap for the firs...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
36,2021-10-25,Elon Musk on his crypto portfolio: I only own ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
37,2021-10-25,Tesla had to roll back and reissue the latest ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
38,2021-10-26,Hertz deal isn’t just tipping point for Tesla ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
39,2021-10-26,Tesla’s China sales have grown to nearly half ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
40,2021-10-26,NTSB head criticizes Tesla’s self-driving feat...,"{'neg': 0.231, 'neu': 0.769, 'pos': 0.0, 'comp...",-0.3400
41,2021-10-27,Elon Musk is now nearly $100 billion richer th...,"{'neg': 0.0, 'neu': 0.798, 'pos': 0.202, 'comp...",0.6486
42,NaT,Ron Baron says he made $6 billion on Tesla inv...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
43,2021-10-28,Tesla is setting the bar for electric vehicles...,"{'neg': 0.0, 'neu': 0.82, 'pos': 0.18, 'compou...",0.2960
44,2021-10-28,"13 years ago, Elon Musk made a bold prediction...","{'neg': 0.0, 'neu': 0.867, 'pos': 0.133, 'comp...",0.3818
45,2021-10-28,Jay Leno: Elon Musk is the reason Tesla is the...,"{'neg': 0.0, 'neu': 0.825, 'pos': 0.175, 'comp...",0.5256
46,2021-10-28,"Ford CEO Farley is ready to ‘bury’ Elon Musk, ...","{'neg': 0.0, 'neu': 0.815, 'pos': 0.185, 'comp...",0.3612
47,2021-10-28,Cramer says Ford CEO ‘ready to bury’ Elon Musk...,"{'neg': 0.0, 'neu': 0.791, 'pos': 0.209, 'comp...",0.5719
48,2021-10-29,Energy secretary defends tax credits for EVs m...,"{'neg': 0.0, 'neu': 0.662, 'pos': 0.338, 'comp...",0.5574
49,2021-11-01,Elon Musk tweets he is willing to spend $6 bil...,"{'neg': 0.148, 'neu': 0.852, 'pos': 0.0, 'comp...",-0.3818

In [42]:
df2 = df1.iloc[:,[0,3]]

In [43]:
df2

          Date  compound
0   2021-09-30    0.0000
1   2021-09-30    0.0000
2   2021-10-02    0.0000
3   2021-10-03   -0.0772
4   2021-10-05    0.0000
..         ...       ...
523 2022-09-21    0.0000
524 2022-09-24    0.0000
525 2022-09-29    0.0000
526 2022-09-30    0.0000
527 2022-09-30    0.0000

[528 rows x 2 columns]

In [44]:
News_Sent = df2.groupby("Date")["compound"].mean()

In [45]:
News_Sent.head(60)

Date
2021-09-30    0.000000
2021-10-02    0.000000
2021-10-03   -0.077200
2021-10-05   -0.130800
2021-10-06   -0.340000
2021-10-07    0.000000
2021-10-08    0.115738
2021-10-09    0.636900
2021-10-10    0.000000
2021-10-11    0.000000
2021-10-12    0.000000
2021-10-14    0.000000
2021-10-15    0.226300
2021-10-17    0.000000
2021-10-18    0.000000
2021-10-19    0.000000
2021-10-20    0.036933
2021-10-21   -0.132467
2021-10-22    0.000000
2021-10-25    0.000000
2021-10-26   -0.113333
2021-10-27    0.648600
2021-10-28    0.427300
2021-10-29    0.557400
2021-11-01   -0.190900
2021-11-02   -0.074950
2021-11-07    0.296000
2021-11-08    0.116643
2021-11-09    0.000000
2021-11-10   -0.093300
2021-11-11    0.000000
2021-11-12    0.020467
2021-11-13   -0.125000
2021-11-15    0.000000
2021-11-16   -0.013180
2021-11-17    0.000000
2021-11-18    0.000000
2021-11-20    0.000000
2021-11-22    0.000000
2021-11-23    0.000000
2021-11-24    0.509350
2021-11-26    0.000000
2021-11-28    0.000000
2021-11-29    0.025800
2021-11-30   -0.229400
2021-12-01   -0.296000
2021-12-03    0.238350
2021-12-04    0.209400
2021-12-06    0.137750
2021-12-07    0.000000
2021-12-10    0.000000
2021-12-13    0.440400
2021-12-14    0.214625
2021-12-15    0.201525
2021-12-20   -0.102700
2021-12-21    0.000000
2021-12-22    0.418400
2021-12-23    0.000000
2021-12-24    0.000000
2021-12-27    0.000000
Name: compound, dtype: float64

In [46]:
News_Sent = pd.DataFrame(News_Sent)

In [47]:
News_Sent

            compound
Date
2021-09-30    0.0000
2021-10-02    0.0000
2021-10-03   -0.0772
2021-10-05   -0.1308
2021-10-06   -0.3400
...              ...
2022-09-20    0.0000
2022-09-21    0.0000
2022-09-24    0.0000
2022-09-29    0.0000
2022-09-30    0.0000

[216 rows x 1 columns]

# Exporting as csv

In [48]:
#News_Sent.to_csv("News_Sent.csv")